import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import portfolioRouter from "./portfolio";
import tradesRouter from "./trades";
import analyticsRouter from "./analytics";
import strategiesRouter from "./strategies";
import riskRouter from "./risk";
import marketRouter from "./market";
import backtestRouter from "./backtest";
import sentimentRouter from "./sentiment";
import notificationsRouter from "./notifications";
import engineRouter from "./engine";
import presetsRouter from "./presets";
import connectionsRouter from "./connections";
import botConfigRouter from "./bot-config";
import userProfileRouter from "./user-profile";
import sentimentSourcesRouter from "./sentiment-sources";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(portfolioRouter);
router.use(tradesRouter);
router.use(analyticsRouter);
router.use(strategiesRouter);
router.use(riskRouter);
router.use(marketRouter);
router.use(backtestRouter);
router.use(sentimentRouter);
router.use(notificationsRouter);
router.use(engineRouter);
router.use(presetsRouter);
router.use(connectionsRouter);
router.use(botConfigRouter);
router.use(userProfileRouter);
router.use(sentimentSourcesRouter);

export default router;
